var trimmedCountryNamesEN = {
    AL: 'Albania',
    AR: 'Argentina',
    AM: 'Armenia',
    AU: 'Australia',
    AT: 'Austria',
    BE: 'Belgium',
    BO: 'Bolivia',
    BA: 'Bosnia and Herzegovina',
    BR: 'Brazil',
    BG: 'Bulgaria',
    CA: 'Canada',
    TD: 'Chad',
    CL: 'Chile',
    CN: 'China',
    CO: 'Colombia',
    CR: 'Costa Rica',
    CU: 'Cuba',
    DK: 'Denmark',
    EC: 'Ecuador',
    EG: 'Egypt',
    FI: 'Finland',
    FR: 'France',
    DE: 'Germany',
    GR: 'Greece',
    GT: 'Guatemala',
    HU: 'Hungary',
    IS: 'Iceland',
    IN: 'India',
    ID: 'Indonesia',
    IE: 'Ireland',
    IT: 'Italy',
    JM: 'Jamaica',
    JP: 'Japan',
    KZ: 'Kazakhstan',
    MX: 'Mexico',
    MN: 'Mongolia',
    NL: 'Netherlands',
    NZ: 'New Zealand',
    KP: 'North Korea',
    NO: 'Norway',
    PK: 'Pakistan',
    PE: 'Peru',
    PH: 'Philippines',
    PL: 'Poland',
    PT: 'Portugal',
    PR: 'Puerto Rico',
    RO: 'Romania',
    RU: 'Russia',
    SA: 'Saudi Arabia',
    RS: 'Serbia',
    SK: 'Slovakia',
    SO: 'Somalia',
    ZA: 'South Africa',
    KR: 'South Korea',
    ES: 'Spain',
    SE: 'Sweden',
    CH: 'Switzerland',
    SY: 'Syria',
    TH: 'Thailand',
    TR: 'Turkey',
    UA: 'Ukraine',
    AE: 'United Arab Emirates',
    GB: 'United Kingdom',
    US: 'United States',
    VE: 'Venezuela',
    VN: 'Vietnam'
  };