var trimmedCountryNamesEN = {
    AF: 'Afghanistan',
    AL: 'Albania',
    DZ: 'Algeria',
    AS: 'American Samoa',
    AO: 'Angola',
    AR: 'Argentina',
    AM: 'Armenia',
    AU: 'Australia',
    AT: 'Austria',
    BY: 'Belarus',
    BE: 'Belgium',
    BJ: 'Benin',
    BM: 'Bermuda',
    BO: 'Bolivia',
    BA: 'Bosnia and Herzegovina',
    BW: 'Botswana',
    BR: 'Brazil',
    BG: 'Bulgaria',
    KH: 'Cambodia',
    CA: 'Canada',
    TD: 'Chad',
    CL: 'Chile',
    CN: 'China',
    CO: 'Colombia',
    CR: 'Costa Rica',
    HR: 'Croatia',
    CU: 'Cuba',
    CZ: 'Czech Republic',
    CD: 'Democratic Republic of the Congo',
    DK: 'Denmark',
    DO: 'Dominican Republic',
    EC: 'Ecuador',
    EG: 'Egypt',
    SV: 'El Salvador',
    FI: 'Finland',
    FR: 'France',
    DE: 'Germany',
    GR: 'Greece',
    GT: 'Guatemala',
    HU: 'Hungary',
    IS: 'Iceland',
    IN: 'India',
    ID: 'Indonesia',
    IE: 'Ireland',
    IT: 'Italy',
    JM: 'Jamaica',
    JP: 'Japan',
    KZ: 'Kazakhstan',
    KE: 'Kenya',
    MX: 'Mexico',
    MN: 'Mongolia',
    NL: 'Netherlands',
    NZ: 'New Zealand',
    NE: 'Niger',
    NG: 'Nigeria',
    KP: 'North Korea',
    NO: 'Norway',
    PK: 'Pakistan',
    PA: 'Panama',
    PG: 'Papua New Guinea',
    PY: 'Paraguay',
    PE: 'Peru',
    PH: 'Philippines',
    PL: 'Poland',
    PT: 'Portugal',
    PR: 'Puerto Rico',
    RO: 'Romania',
    RU: 'Russia',
    SA: 'Saudi Arabia',
    RS: 'Serbia',
    SG: 'Singapore',
    SK: 'Slovakia',
    SO: 'Somalia',
    ZA: 'South Africa',
    KR: 'South Korea',
    ES: 'Spain',
    SE: 'Sweden',
    CH: 'Switzerland',
    SY: 'Syria',
    TH: 'Thailand',
    TR: 'Turkey',
    UG: 'Uganda',
    UA: 'Ukraine',
    AE: 'United Arab Emirates',
    GB: 'United Kingdom',
    US: 'United States',
    VE: 'Venezuela',
    VN: 'Vietnam',
  };